#include "encode.h"

#include <cvc5/cvc5.h>
#include <cvc5/cvc5_parser.h>
#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_split.h"
#include "aspif.h"
#include "ground.h"
#include "macros.h"
#include "normalize.h"
#include "parse.h"
#include "test_macros.h"

using ::testing::AllOf;
using ::testing::Contains;
using ::testing::Each;
using ::testing::ElementsAre;
using ::testing::HasSubstr;
using ::testing::Not;

namespace {

// Parses, normalizes, and grounds `source`, then encodes it.
absl::StatusOr<std::string> encode_source(const std::string& source) {
  Parser parser(source);
  ASSIGN_OR_RETURN(auto program, parser.parse_program());
  RETURN_IF_ERROR(normalize(*program));
  ASSIGN_OR_RETURN(aspif::Program grounded, ground(*program));
  return encode_smtlib(grounded);
}

// The lines of a script that are neither comments nor blank.
std::vector<std::string> commands(const std::string& script) {
  std::vector<std::string> lines;
  for (std::string_view line : absl::StrSplit(script, '\n')) {
    if (line.empty() || line.front() == ';') continue;
    lines.push_back(std::string(line));
  }
  return lines;
}

// The comment lines of a script, so that a test can name one of them.
std::vector<std::string> comments(const std::string& script) {
  std::vector<std::string> lines;
  for (std::string_view line : absl::StrSplit(script, '\n')) {
    if (line.empty() || line.front() != ';') continue;
    lines.push_back(std::string(line));
  }
  return lines;
}

// Runs `script` through cvc5's own SMT-LIB parser and returns what the commands
// printed. cvc5 reads it back with none of the knowledge that wrote it, which
// is what says the text really is SMT-LIB and not just close to it.
absl::StatusOr<std::string> run_script(const std::string& script) {
  cvc5::TermManager tm;
  cvc5::Solver solver(tm);
  cvc5::parser::SymbolManager sm(tm);
  cvc5::parser::InputParser parser(&solver, &sm);
  parser.setStringInput(cvc5::modes::InputLanguage::SMT_LIB_2_6, script,
                        "encode_test");
  std::stringstream out;
  try {
    while (true) {
      cvc5::parser::Command command = parser.nextCommand();
      if (command.isNull()) break;
      command.invoke(&solver, &sm, out);
    }
  } catch (const std::exception& e) {
    return absl::InvalidArgumentError(e.what());
  }
  return out.str();
}

// The answer to the script's (check-sat), which cvc5 prints on a line of its
// own before anything (get-model) prints.
absl::StatusOr<std::string> check_sat_of(const std::string& source) {
  ASSIGN_OR_RETURN(const std::string script, encode_source(source));
  ASSIGN_OR_RETURN(const std::string output, run_script(script));
  return output.substr(0, output.find('\n'));
}

// Two atoms, each holding where the other does not, is the smallest program
// with more than one answer set. Its whole script is stated here, so a change
// to the translation shows up as a diff.
TEST(EncodeTest, TranslatesAChoiceOfTwoAtoms) {
  auto script = encode_source(R"(
    a :- not b.
    b :- not a.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(
      commands(*script),
      ElementsAre("(set-option :produce-models true)", "(set-logic QF_IDL)",
                  "(declare-const b Bool)", "(declare-const a Bool)",
                  // Every rule is satisfied.
                  "(assert (=> (not a) b))", "(assert (=> (not b) a))",
                  // Every atom that holds is supported.
                  "(assert (=> b (not a)))", "(assert (=> a (not b)))",
                  "(check-sat)", "(get-model)"));
  // A section with nothing in it is left out, and this program has neither a
  // ranking nor a query.
  EXPECT_THAT(comments(*script),
              ElementsAre("; Generated by pgass --encode=smtlib.",
                          "; Constants", "; Rules", "; Support"));
}

// A constant is named after the symbol the program prints for its atom, so a
// model reads as a set of ASP atoms. 'p(1)' comes out quoted, a bare SMT-LIB
// symbol holding no parentheses or commas.
TEST(EncodeTest, NamesConstantsAfterThePrintedSymbols) {
  auto script = encode_source(R"(
    p(1) :- not q(1).
    q(1) :- not p(1).
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script),
              AllOf(Contains("(declare-const |p(1)| Bool)"),
                    Contains("(declare-const |q(1)| Bool)"),
                    Contains("(assert (=> (not |q(1)|) |p(1)|))")));
  // Every symbol is the name of a constant here, so the header keeps no table
  // of the ones that are not.
  EXPECT_THAT(comments(*script), Each(Not(HasSubstr(" : "))));
}

// An atom the program prints nothing for keeps a name made from its id. The
// aggregate here becomes rules over predicates normalization invents, which are
// kept out of the output.
TEST(EncodeTest, NumbersTheAtomsNothingIsPrintedFor) {
  auto script = encode_source(R"(
    item(a). item(b).
    picked(X) :- item(X), not skipped(X).
    skipped(X) :- item(X), not picked(X).
    :- #count{ X : picked(X) } > 1.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script), Contains(HasSubstr("(declare-const a")));
}

// A program whose atoms lie on no positive cycle needs no ranking, which leaves
// the translation as plain completion.
TEST(EncodeTest, DeclaresNoLevelWithoutAPositiveCycle) {
  auto script = encode_source(R"(
    a :- not b.
    b :- not a.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script), Each(Not(HasSubstr("lvl"))));
}

// A positive cycle gets one integer per atom on it, and a difference between
// two of them per rule that goes round the cycle.
TEST(EncodeTest, RanksTheAtomsOfAPositiveCycle) {
  auto script = encode_source(R"(
    p :- not q.
    q :- not p.
    a :- p.
    a :- b.
    b :- a.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script),
              AllOf(Contains("(declare-const |lvl(a)| Int)"),
                    Contains("(declare-const |lvl(b)| Int)"),
                    Contains("(assert (=> b (and a (>= (- |lvl(b)| "
                             "|lvl(a)|) 1))))")));
  EXPECT_THAT(comments(*script), AllOf(Contains("; Level variables"),
                                       Contains("; Level ranking")));
}

// A query asks whether every answer set satisfies it, so the script asserts it
// negated. A model is an answer set the query fails in.
TEST(EncodeTest, AssertsTheNegatedQuery) {
  auto script = encode_source(R"(
    p(1) :- not q(1).
    q(1) :- not p(1).
    q(1)?
  )");
  ASSERT_OK(script);
  EXPECT_THAT(comments(*script), Contains("; Query"));
  EXPECT_THAT(commands(*script), Contains("(assert (not |q(1)|))"));
  // The comment names the query the way the program wrote it.
  EXPECT_THAT(*script, HasSubstr("The query q(1)? holds where"));
}

// A program read as aspif carries the atoms its query matched but not the text
// of the query, aspif having no query statement, so the comment says 'the
// query' and the script is otherwise the same.
TEST(EncodeTest, NamesTheQueryPlainlyWhereTheTextIsGone) {
  aspif::Program prog;
  const aspif::Atom a = prog.new_atom();
  const aspif::Atom b = prog.new_atom();
  prog.rules.push_back(aspif::Rule{.head = {a}, .body = {-b}});
  prog.rules.push_back(aspif::Rule{.head = {b}, .body = {-a}});
  prog.outputs.push_back(aspif::Output{.name = "a", .condition = {a}});
  prog.query.emplace(std::vector<aspif::Lit>{a});

  auto script = encode_smtlib(prog);
  ASSERT_OK(script);
  EXPECT_THAT(*script, HasSubstr("The query holds where"));
  EXPECT_THAT(commands(*script), Contains("(assert (not a))"));
}

// A query no atom matched fails in every answer set, so there is nothing to
// assert and the encoding stands as it is. 'sat' says an answer set is there
// to fail the query, which is the answer no.
TEST(EncodeTest, AssertsNothingForAQueryNoAtomMatched) {
  auto script = encode_source(R"(
    p(1).
    q(2)?
  )");
  ASSERT_OK(script);
  EXPECT_THAT(comments(*script), Contains("; Query"));
  EXPECT_THAT(commands(*script), Each(Not(HasSubstr("q(2)"))));

  auto answer = check_sat_of(R"(
    p(1).
    q(2)?
  )");
  ASSERT_OK(answer);
  EXPECT_EQ(*answer, "sat");
}

// The one way a query no atom matched holds is for the program to have no
// answer set, and 'unsat' is how the script says that.
TEST(EncodeTest, IsUnsatWhereAQueryNoAtomMatchedHolds) {
  auto answer = check_sat_of(R"(
    a :- not a.
    q(2)?
  )");
  ASSERT_OK(answer);
  EXPECT_EQ(*answer, "unsat");
}

// Each atom a query matched is asked about under a negation of its own, so a
// query of several atoms is several check-sats, each in a scope the next one
// does not inherit.
TEST(EncodeTest, AsksAboutEachAtomOfAQueryOnItsOwn) {
  auto script = encode_source(R"(
    p(1). p(2).
    p(X)?
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script),
              ElementsAre("(set-option :produce-models true)",
                          "(set-option :incremental true)",
                          "(set-logic QF_IDL)", "(declare-const |p(1)| Bool)",
                          "(declare-const |p(2)| Bool)",
                          "(assert (=> true |p(1)|))",
                          "(assert (=> true |p(2)|))",
                          "(assert (=> |p(1)| true))",
                          "(assert (=> |p(2)| true))",
                          // One question per atom, and no question at the end.
                          "(push 1)", "(assert (not |p(1)|))", "(check-sat)",
                          "(pop 1)", "(push 1)", "(assert (not |p(2)|))",
                          "(check-sat)", "(pop 1)"));
  EXPECT_THAT(*script, HasSubstr("The query p(X)? matched 2 atoms"));
}

// A comment holds a name the program chose, of any length, so the lines are
// wrapped rather than laid out by hand.
TEST(EncodeTest, WrapsACommentAroundALongQuery) {
  auto script = encode_source(R"(
    connection(amsterdam, brussels). connection(brussels, cologne).
    reachable(X, Y) :- connection(X, Y), not severed(X, Y).
    severed(X, Y) :- connection(X, Y), not reachable(X, Y).
    reachable(amsterdam, Destination)?
  )");
  ASSERT_OK(script);
  for (const std::string& line : comments(*script)) {
    EXPECT_LE(line.size(), 78u) << line;
  }
  EXPECT_THAT(*script,
              HasSubstr("The query reachable(amsterdam, Destination)?"));
}

// Both atoms hold in the one answer set, so both questions come back unsat,
// and both atoms answer the query.
TEST(EncodeTest, CvcReadsBackAQueryOfSeveralAtoms) {
  auto script = encode_source(R"(
    p(1). p(2).
    p(X)?
  )");
  ASSERT_OK(script);
  auto output = run_script(*script);
  ASSERT_OK(output);
  EXPECT_EQ(*output, "unsat\nunsat\n");
}

// An atom that fails in some answer set is answered sat, and one that holds in
// all of them is answered unsat, in the order the atoms were matched.
TEST(EncodeTest, AnswersEachSubstitutionOfAQuery) {
  auto script = encode_source(R"(
    p(1).
    p(2) :- not q.
    q :- not p(2).
    p(X)?
  )");
  ASSERT_OK(script);
  auto output = run_script(*script);
  ASSERT_OK(output);
  EXPECT_EQ(*output, "unsat\nsat\n");
}

// A weight body whose weights all differ adds up literals, which no difference
// logic atom can say, so the whole script moves to QF_LIA.
TEST(EncodeTest, PicksLinearArithmeticForAWeightBody) {
  auto script = encode_source(R"(
    item(a). item(b).
    picked(X) :- item(X), not skipped(X).
    skipped(X) :- item(X), not picked(X).
    :- #sum{ 2,a : picked(a) ; 3,b : picked(b) } > 4.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script), Contains("(set-logic QF_LIA)"));
}

// Counting is a question about the literals, not a sum of them, so a #count
// leaves the script in difference logic. 'more than one of two' is both of
// them, which is what the totalizer boils down to here.
TEST(EncodeTest, CountsWithoutArithmetic) {
  auto script = encode_source(R"(
    item(a). item(b).
    picked(X) :- item(X), not skipped(X).
    skipped(X) :- item(X), not picked(X).
    :- #count{ X : picked(X) } > 1.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(*script, AllOf(HasSubstr("(set-logic QF_IDL)"),
                             HasSubstr("(and |picked(a)| |picked(b)|)"),
                             Not(HasSubstr("(ite ")), Not(HasSubstr("(+ "))));
}

// A #min or #max grounds to plain rules over one atom per element tuple, never
// to a weight body, so difference logic still covers the program.
TEST(EncodeTest, TranslatesAMinAggregate) {
  auto script = encode_source(R"(
    { p(1) }. { p(3) }.
    q :- #min{ X : p(X) } >= 3.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(*script, AllOf(HasSubstr("(set-logic QF_IDL)"),
                             HasSubstr("(assert (=> (not |p(1)|) q))")));
}

// No one script can state the least cost of a priority level, which takes
// repeated queries under a falling bound, so the script names each level's cost
// and leaves the walk down to its reader.
TEST(EncodeTest, NamesTheCostOfEachPriorityLevel) {
  auto script = encode_source(R"(
    a :- not b.
    b :- not a.
    :~ a. [1@1]
    :~ b. [2@2]
  )");
  ASSERT_OK(script);
  // A weak constraint's body becomes an atom of its own, which the program
  // prints nothing for, so a cost adds up numbered atoms rather than a and b.
  // The most important level comes first, and no cost is asserted.
  EXPECT_THAT(commands(*script),
              AllOf(Contains("(define-fun cost@2 () Int (ite a4 2 0))"),
                    Contains("(define-fun cost@1 () Int (ite a3 1 0))"),
                    Each(Not(AllOf(HasSubstr("assert"), HasSubstr("cost@")))),
                    Contains("(check-sat)")));
  EXPECT_THAT(comments(*script), Contains("; Weak constraints"));

  auto answer = run_script(*script);
  ASSERT_OK(answer);
  EXPECT_THAT(*answer, HasSubstr("sat"));
}

// Two minimize statements of one priority are one level, the cost of a level
// being the total over its literals.
TEST(EncodeTest, AddsUpOnePriorityLevelAtATime) {
  auto script = encode_source(R"(
    a :- not b.
    b :- not a.
    :~ a. [1@1]
    :~ b. [3@1]
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script),
              Contains("(define-fun cost@1 () Int (+ (ite a3 1 0) "
                       "(ite a4 3 0)))"));
}

// Where two head atoms of one rule lie on a common positive cycle, the
// completion admits models that are not answer sets, so the script asserts the
// minimality check itself. It quantifies over subsets, which moves the script
// out of a quantifier free logic.
TEST(EncodeTest, AssertsMinimalityForAHeadCycle) {
  auto script = encode_source(R"(
    a | b.
    a :- b.
    b :- a.
  )");
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script),
              AllOf(Contains("(set-logic ALL)"),
                    Contains(HasSubstr("(assert (forall ((|sub(a)| Bool) "
                                       "(|sub(b)| Bool))"))));
  EXPECT_THAT(comments(*script), Contains("; Minimality"));

  // {a, b} passes the check, a and b holding each other up around the cycle,
  // so it is the answer set and the script's only model.
  auto output = run_script(*script);
  ASSERT_OK(output);
  EXPECT_THAT(*output, AllOf(HasSubstr("sat"),
                             HasSubstr("(define-fun a () Bool true)"),
                             HasSubstr("(define-fun b () Bool true)")));
}

// The check earns its place here: {y, ny, s} models the completion, and the
// smaller {y} models the reduct under it, so it is no answer set. The answer
// sets are {y} and {ny}, and s holds in neither.
TEST(EncodeTest, MinimalityRulesOutAModelASubsetUndercuts) {
  auto script = encode_source(R"(
    y | ny.
    s :- y, ny.
    y :- s.
    ny :- s.
  )");
  ASSERT_OK(script);
  auto output = run_script(*script);
  ASSERT_OK(output);
  EXPECT_THAT(*output, AllOf(HasSubstr("sat"),
                             HasSubstr("(define-fun s () Bool false)")));
}

TEST(EncodeTest, CvcReadsBackASatisfiableScript) {
  auto answer = check_sat_of(R"(
    a :- not b.
    b :- not a.
  )");
  ASSERT_OK(answer);
  EXPECT_EQ(*answer, "sat");
}

// A cycle nothing outside it supports holds in no answer set, and the
// constraint rules the empty one out, so the script is unsatisfiable. This is
// the level ranking doing its work on the way through cvc5's parser.
TEST(EncodeTest, CvcReadsBackAnUnsatisfiableScript) {
  auto answer = check_sat_of(R"(
    a :- b.
    b :- a.
    :- not a.
  )");
  ASSERT_OK(answer);
  EXPECT_EQ(*answer, "unsat");
}

// The model cvc5 finds is an answer set, in the program's own names. Here it is
// the only one, holding p and q and not r.
TEST(EncodeTest, TheModelOfTheScriptIsTheAnswerSet) {
  auto script = encode_source(R"(
    p.
    q :- p.
    r :- not p.
  )");
  ASSERT_OK(script);
  auto output = run_script(*script);
  ASSERT_OK(output);
  EXPECT_THAT(*output, AllOf(HasSubstr("(define-fun p () Bool true)"),
                             HasSubstr("(define-fun q () Bool true)"),
                             HasSubstr("(define-fun r () Bool false)")));
}

// aspif lets a symbol hold under several literals at once, which no one
// constant can be named after, so the header says what it needs instead.
// Nothing pgass grounds looks like this, but a program read as aspif can.
TEST(EncodeTest, SpellsOutASymbolNoConstantIsNamedAfter) {
  aspif::Program prog;
  const aspif::Atom a = prog.new_atom();
  const aspif::Atom b = prog.new_atom();
  prog.rules.push_back(aspif::Rule{.head = {a}, .body = {-b}});
  prog.rules.push_back(aspif::Rule{.head = {b}, .body = {-a}});
  prog.outputs.push_back(aspif::Output{.name = "a", .condition = {a}});
  prog.outputs.push_back(aspif::Output{.name = "both", .condition = {a, -b}});

  auto script = encode_smtlib(prog);
  ASSERT_OK(script);
  EXPECT_THAT(comments(*script), Contains(";   both : a (not a2)"));
}

// The fallback name of an atom nothing is printed for can collide with a symbol
// the program prints for another atom. The fallback gives way.
TEST(EncodeTest, KeepsFallbackNamesClearOfPrintedSymbols) {
  aspif::Program prog;
  const aspif::Atom printed = prog.new_atom();
  const aspif::Atom hidden = prog.new_atom();
  prog.rules.push_back(aspif::Rule{.head = {hidden}});
  prog.rules.push_back(aspif::Rule{.head = {printed}, .body = {hidden}});
  // The symbol of atom 1 is the name atom 2 would otherwise fall back on.
  prog.outputs.push_back(aspif::Output{.name = "a2", .condition = {printed}});

  auto script = encode_smtlib(prog);
  ASSERT_OK(script);
  EXPECT_THAT(commands(*script), AllOf(Contains("(declare-const a2 Bool)"),
                                       Contains("(declare-const _a2 Bool)")));
}

}  // namespace
